# Generated by Django 2.2.4 on 2019-08-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_link', models.CharField(max_length=250)),
                ('photo_link', models.CharField(max_length=250)),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
